### ISSUE TITLE
Google Play requirements to republish Exodus application

### ISSUE THREAD

**Issue by codeurimpulsif** [Exodus-Privacy/exodus-android-app#111]
## Goal
Republish the Exodus application on the Google Play Store.

## Problems

- Since 2021-08-02 the exodus application is no longer available on the Google Play Store
- Play Store's Eligibility Issue: APK requires valid privacy policy and prominent disclosure

## Informations

- Google Play Store email:
  > Your app is uploading users' Installed Application information to https://reports.exodus-privacy.eu.org without a prominent disclosure. Make sure to also post a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.

- Documentation about "Prominent Disclosure & Consent Requirement": https://support.google.com/googleplay/android-developer/answer/10144311

## Tasks

- [ ] Add the privacy policy in the Play Store Developer Console
- [ ] Add the privacy policy in the application

**Comment by theimpulson** [comment]
Can someone provide me an official privacy policy after discussing it with the team and related legal parties if possible?

**Comment by pnu-s** [comment]
@theimpulson We are currently finalizing it. This being said, we will probably add a link rather than the policy itself in the application, so that we can update it without publishing a new version of the app.

I will be hosted on https://exodus-privacy.eu.org/en/ but I can try to add a dummy page so that we provide you a more precise link.

**Comment by pnu-s** [comment]
It will most probably be: https://exodus-privacy.eu.org/en/page/privacy-policy/
