### ISSUE TITLE
Improve links support on trackers fragment

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#173]
On latest debug version,
Links on trackers from description is show like
`[Crunchbase, 01](https://www.crunchbase.com/organization/databerries)`

Update and show on app like on website:
[Crunchbase, 01](https://www.crunchbase.com/organization/databerries)

**Comment by Jean-BaptisteC** [comment]
Idem for italics
On app:
`*A Java library which gives you unparalleled insight into what your code does in production.*`

On website
*A Java library which gives you unparalleled insight into what your code does in production.*

**Comment by theimpulson** [comment]
I was unaware that the description was in markdown format. This should now be fixed with https://github.com/Exodus-Privacy/exodus-android-app/commit/63d9446cfe52d9fa09f1aa2d2e3a2211cfd58e01. Old version was parsing markdown manually while on the rewrite I have switched to https://github.com/noties/Markwon.

**Comment by Jean-BaptisteC** [comment]
Markdown => OK
