### ISSUE TITLE
Exodus can't analyze com.heytap.pictorial

### ISSUE THREAD

**Issue by Krawei** [Exodus-Privacy/exodus-android-app#249]
Dear Devs,

I try to analyze the app mentioned above (https://play.google.com/store/apps/details?id=com.heytap.pictorial) via your website https://reports.exodus-privacy.eu.org/de/analysis/submit/ but it doesn't work.

The websites presents a "Analyze done" page after a while but with the embedded error text "can't download APK"
![Screenshot_2023-02-24-08-34-20-59_80c65855c2fd87fe33c18da258042f3e](https://user-images.githubusercontent.com/25485657/221149045-fb10f71b-79f3-4763-b81a-4aec6514fa20.jpg)

.

Could you please implement a higher verbose level or an APK upload, please? That would solve the issue of regional restricted apps in Google Play store.

Kind Regards,

K.

**Comment by yoshimo** [comment]
Could also be a limitation to devices with certain features  like vendor, nfc enabled or so. The verbosity really needs to be higher.

**Comment by Jean-BaptisteC** [comment]
Is not possible to analyze app because, we try to download app created by Oppo (developers can select which devices can donwload app) on Pixel phone, created by Google (device used on exodus platform to download apk)
If you want, you can analyze app in local with [exodus-standalone](https://github.com/Exodus-Privacy/exodus-standalone)
