### ISSUE TITLE
Yalp packages are still not recognized properly

### ISSUE THREAD

**Issue by dertuxmalwieder** [Exodus-Privacy/exodus-android-app#36]
Exodus 1.1.0 should have added detection for Yalp store apps. However, on a phone *without* a Google account, it doesn't. I had a friend who avoids Google stuff install Exodus from F-Droid yesterday, but it refused to show any of his Yalp apps. (OnePlus 3, newest updates.)

Is there still a requirement for Google anywhere in the code?

**Comment by beerisgood** [comment]
For me it works with apps installed from Yalp
LineageOS 15.1 - OnePlus 2

But I need to restart the app after first scan.

**Comment by Schoumi** [comment]
No google stuff needed. 
Could you give me names of some apps not properly detected? or if you don't want, can you check on https://reports.exodus-privacy.eu.org/fr/ if it has already been analysed once. If the app has been analysed, it should have an UAID and only with these two conditions i can add Yalp installed apps. Without these i can't be sure of the installation source.

I can't magically detect all apps installed threw Yalp since their not properly identified as installed by Yalp in the system. I analyse certificate signature and package name to identify these apps. To compare the result i get and the result we have in database (UAID)
(i need to be more precise on this somewhere)

For exemple: https://reports.exodus-privacy.eu.org/fr/reports/48626/ can be found because it has been analysed once (no matter of what version) and it has an UAID (UAID : 98892A86D0683E5A426581AD78ED8C9263B5833F found in APK Fingerprint in the reports)

**Comment by dertuxmalwieder** [comment]
They're mostly analyzed - in fact, I even added some of them myself. Or do the Play Store versions have different UAIDs than the Yalp versions? (That wouldn't make much sense.) Sadly, I won't see him before next Tuesday.

**Comment by dertuxmalwieder** [comment]
Those seem to be the same UAIDs... Hmm.

**Comment by dertuxmalwieder** [comment]
The app still claims that the only source that is searched is Google Play.

**Comment by Schoumi** [comment]
Because it's still true. App installed by Yalp are from the Google Play. Using Yalp, Aurora or any other app that use the play store as a source don't change the source. If you don't give me apps installed by Yalp not correctly detected i can't do anything for you.

**Comment by dertuxmalwieder** [comment]
He said the app suddenly started working as intended during his vacation.
