### ISSUE TITLE
Applications not detected when installed over third party stores?

### ISSUE THREAD

**Issue by dominikheinz** [Exodus-Privacy/exodus-android-app#75]
Having installed LineageOS with microG on my phone, most of my apps I install are from F-Droid.
However, for some cases I have to use non-open source apps. 
However, I do not have installed the Google Playstore, but instead Aurora store, which acts as a proxy for the Playstore to download apps from the Playstore anonymously.

After I installed Exodus, it is not detecting the installed apps, which definitely have trackers.
"_It appears that you don't have any apps installed for the source we test (Google play store)_"

Is there a way to not rely on the Playstore to analyze the installed apps for trackers?

**Comment by Schoumi** [comment]
It should detect app install from Yalp or Aurora store only if we have already analyzed the app from the playstore so we have the signature of the application. Since we don't know the real source of the app except for ones installed by the play store, we use the signature of the app to determine if it's the same as we know. The problem of this is that we detect only app we know even if other apps are from the Play Store downloaded through other stores (Yalp/Aurora/...)

Could you check if the app you've install with Aurora is available here https://reports.exodus-privacy.eu.org/ If not it's normal. If we have analyzed the app and it's not available on you're phone in the app. i'll check that.

**Comment by dominikheinz** [comment]
I do have installed applications that are listed on the exodus page.

However, a reinstall of the exodus app seems to have fixed the problem. 
I cannot pinpoint why it did not detect any of the apps before.
